name: first_android_project
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  font_awesome_flutter: any
  bloc: any

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3

  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true

  assets:
    - lib/icons/


